[tool.poetry]
name = "miappe-api"
version = "0.1.0"
description = "Python API for MIAPPE metadata dataset"
authors = ["hoangson <lehoangsonsg@gmail.com>"]
readme = "README.md"
repository = "https://github.com/haryle/MIAPPE_API"
packages = [
    { include = "miappe" }
]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.3"
pyyaml = "^6.0.1"
pandas = "^2.1.4"
pycountry = "^23.12.11"
openpyxl = "^3.1.2"
typer = {extras = ["all"], version = "^0.9.0"}


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-cov = "^4.1.0"
ruff = "^0.1.15"
black = "^23.9.0"
pre-commit = "^3.4.0"
typer = "^0.9.0"


[tool.poetry.group.isa.dependencies]
networkx = "^3.2.1"
iso8601 = "^2.1.0"
lxml = "^5.1.0"
requests = "^2.31.0"
graphene = "^3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.report]
exclude_also = [
    "def __repr__",
    "@(abc\\.)?abstractmethod",
    "def __getattr__",
    "if TYPE_CHECKING:"
]

[tool.poetry.scripts]
miappe = "miappe.cli.main:app"


[tool.ruff]
line-length = 88
src = ["miappe"]
target-version = "py311"
