on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      python-version:
        required: false
        type: string
        default: "3.11"

jobs:
  mypy:
    runs-on: ${{inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: pdm-project/setup-pdm@v4
        name: Set up PDM
        with:
          python-version: "3.11"
          allow-python-prereleases: false
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm install -G:all

      - name: Run mypy
        run: pdm run mypy

  pyright:
    runs-on: ${{inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: pdm-project/setup-pdm@v4
        name: Set up PDM
        with:
          python-version: "3.11"
          allow-python-prereleases: false
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm install -G:all

      - name: Run pyright
        run: pdm run pyright
